include components/common/thirdparty/100ask_r128_demos/module_driver/module_driver_100ask.mk

obj-$(CONFIG_USE_100ASK_MODULE_DRIVER_SPI_FLASH_W25Q64) += driver_spiflash_w25q64.o
obj-$(CONFIG_USE_100ASK_MODULE_DRIVER_IR_RECEIVER) += driver_spiflash.o
