include components/common/thirdparty/100ask_r128_demos/module_driver/module_driver_100ask.mk

PRJ_SRC_DIR = src

obj-$(CONFIG_USE_100ASK_MODULE_DRIVER_IIC_OLED) 		+= $(PRJ_SRC_DIR)/iic_oled/
obj-$(CONFIG_USE_100ASK_MODULE_DRIVER_SPI_LCD) 			+= $(PRJ_SRC_DIR)/spi_lcd/
obj-$(CONFIG_USE_100ASK_MODULE_DRIVER_PASSIVE_BUZZER) 	+= $(PRJ_SRC_DIR)/passive_buzzer/
obj-$(CONFIG_USE_100ASK_MODULE_DRIVER_ROTARY_ENCODER) 	+= $(PRJ_SRC_DIR)/rotary_encoder/
obj-$(CONFIG_USE_100ASK_MODULE_DRIVER_IR_RECEIVER) 		+= $(PRJ_SRC_DIR)/ir_receiver/
obj-$(CONFIG_USE_100ASK_MODULE_DRIVER_SPI_FLASH) 		+= $(PRJ_SRC_DIR)/spi_flash/
obj-$(CONFIG_USE_100ASK_MODULE_DRIVER_DHT11) 			+= $(PRJ_SRC_DIR)/dht11/
obj-$(CONFIG_USE_100ASK_MODULE_DRIVER_SERVO) 			+= $(PRJ_SRC_DIR)/servo/


obj-y += $(PRJ_SRC_DIR)/module_driver_100ask_test_main.o
